/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Thu Jun 15 16:27:07 2023.
 */

#include <string.h>

#include "e3.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int e3_bms_675_pack(
    uint8_t *dst_p,
    const struct e3_bms_675_t *src_p,
    size_t size)
{
    uint16_t h_soc;
    uint16_t l_soc;
    uint8_t real_soc;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    real_soc = (uint8_t)src_p->real_soc;
    dst_p[2] |= pack_left_shift_u8(real_soc, 0u, 0xffu);
    h_soc = (uint16_t)src_p->h_soc;
    dst_p[4] |= pack_right_shift_u16(h_soc, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(h_soc, 0u, 0xffu);
    l_soc = (uint16_t)src_p->l_soc;
    dst_p[6] |= pack_right_shift_u16(l_soc, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(l_soc, 0u, 0xffu);

    return (8);
}

int e3_bms_675_unpack(
    struct e3_bms_675_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t h_soc;
    uint16_t l_soc;
    uint8_t real_soc;

    if (size < 8u) {
        return (-EINVAL);
    }

    real_soc = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->real_soc = (int8_t)real_soc;
    h_soc = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    h_soc |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->h_soc = (int16_t)h_soc;
    l_soc = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    l_soc |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->l_soc = (int16_t)l_soc;

    return (0);
}

bool e3_bms_675_real_soc_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_675_h_soc_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_675_l_soc_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int e3_bms_104_pack(
    uint8_t *dst_p,
    const struct e3_bms_104_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->batt_volt, 6u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->batt_volt, 2u, 0xfcu);
    dst_p[1] |= pack_right_shift_u16(src_p->link_volt, 12u, 0x03u);
    dst_p[2] |= pack_right_shift_u16(src_p->link_volt, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->link_volt, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->batt_curr, 10u, 0x0fu);
    dst_p[4] |= pack_right_shift_u16(src_p->batt_curr, 2u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->batt_curr, 6u, 0xc0u);
    dst_p[5] |= pack_right_shift_u16(src_p->soc, 4u, 0x3fu);
    dst_p[6] |= pack_left_shift_u16(src_p->soc, 4u, 0xf0u);
    dst_p[6] |= pack_left_shift_u8(src_p->message_counter, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->check_sum, 0u, 0xffu);

    return (8);
}

int e3_bms_104_unpack(
    struct e3_bms_104_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->batt_volt = unpack_left_shift_u16(src_p[0], 6u, 0xffu);
    dst_p->batt_volt |= unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->link_volt = unpack_left_shift_u16(src_p[1], 12u, 0x03u);
    dst_p->link_volt |= unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->link_volt |= unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->batt_curr = unpack_left_shift_u16(src_p[3], 10u, 0x0fu);
    dst_p->batt_curr |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);
    dst_p->batt_curr |= unpack_right_shift_u16(src_p[5], 6u, 0xc0u);
    dst_p->soc = unpack_left_shift_u16(src_p[5], 4u, 0x3fu);
    dst_p->soc |= unpack_right_shift_u16(src_p[6], 4u, 0xf0u);
    dst_p->message_counter = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->check_sum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_104_batt_volt_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

bool e3_bms_104_link_volt_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

bool e3_bms_104_batt_curr_is_in_range(uint16_t value)
{
    return (value <= 14000u);
}

bool e3_bms_104_soc_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

bool e3_bms_104_message_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_bms_104_check_sum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_bms_355_pack(
    uint8_t *dst_p,
    const struct e3_bms_355_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->bms_peak_dis_pwr_30s, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->bms_peak_dis_pwr_30s, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_ctn_dis_pwr, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->bms_ctn_dis_pwr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->bms_peak_chg_pwr_30s, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->bms_peak_chg_pwr_30s, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->bms_ctn_chg_pwr, 8u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->bms_ctn_chg_pwr, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_355_rolling_counter, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_355_checksum, 0u, 0xffu);

    return (8);
}

int e3_bms_355_unpack(
    struct e3_bms_355_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_peak_dis_pwr_30s = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->bms_peak_dis_pwr_30s |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->bms_ctn_dis_pwr = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->bms_ctn_dis_pwr |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->bms_peak_chg_pwr_30s = unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->bms_peak_chg_pwr_30s |= unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->bms_ctn_chg_pwr = unpack_left_shift_u16(src_p[4], 8u, 0x0fu);
    dst_p->bms_ctn_chg_pwr |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->bms_355_rolling_counter = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->bms_355_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_355_bms_peak_dis_pwr_30s_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_bms_355_bms_ctn_dis_pwr_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_bms_355_bms_peak_chg_pwr_30s_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_bms_355_bms_ctn_chg_pwr_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_bms_355_bms_355_rolling_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_bms_355_bms_355_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_bms_356_pack(
    uint8_t *dst_p,
    const struct e3_bms_356_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->bms_peak_dis_pwr_10s, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->bms_peak_dis_pwr_10s, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_peak_chg_pwr_10s, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->bms_peak_chg_pwr_10s, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_pow_bat_allow_int_char_sta, 4u, 0x30u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_356_message_counter, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_356_check_sum, 0u, 0xffu);

    return (8);
}

int e3_bms_356_unpack(
    struct e3_bms_356_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_peak_dis_pwr_10s = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->bms_peak_dis_pwr_10s |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->bms_peak_chg_pwr_10s = unpack_left_shift_u16(src_p[1], 8u, 0x0fu);
    dst_p->bms_peak_chg_pwr_10s |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->bms_pow_bat_allow_int_char_sta = unpack_right_shift_u8(src_p[5], 4u, 0x30u);
    dst_p->bms_356_message_counter = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->bms_356_check_sum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_356_bms_peak_dis_pwr_10s_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_bms_356_bms_peak_chg_pwr_10s_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_bms_356_bms_pow_bat_allow_int_char_sta_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_356_bms_356_message_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_bms_356_bms_356_check_sum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_bms_109_pack(
    uint8_t *dst_p,
    const struct e3_bms_109_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_pre_chg_st, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_work_status, 3u, 0x38u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_fault_level, 0u, 0x07u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_hv_ctrl_req, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_neg_relay_st, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_pre_relay_st, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_pos_relay_st, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_chg_status_t_box, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_s2switch_req, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_dis_chg_status, 5u, 0x60u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_crash_sig_st, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_mode, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_chg_status, 5u, 0xe0u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_cc2_sta, 2u, 0x0cu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_vcu_wakeup_bms, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_hv_interlock_status, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_onc_con_st, 0u, 0x07u);
    dst_p[5] |= pack_right_shift_u16(src_p->bms_vcu_soc, 2u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->bms_vcu_soc, 6u, 0xc0u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_bool_battbalance_act, 5u, 0x20u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_109_rolling_counter, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_109_checksum, 0u, 0xffu);

    return (8);
}

int e3_bms_109_unpack(
    struct e3_bms_109_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_pre_chg_st = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->bms_work_status = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->bms_fault_level = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->bms_hv_ctrl_req = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->bms_neg_relay_st = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->bms_pre_relay_st = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->bms_pos_relay_st = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->bms_chg_status_t_box = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->bms_s2switch_req = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->bms_dis_chg_status = unpack_right_shift_u8(src_p[2], 5u, 0x60u);
    dst_p->bms_crash_sig_st = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->bms_mode = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->bms_chg_status = unpack_right_shift_u8(src_p[3], 5u, 0xe0u);
    dst_p->bms_cc2_sta = unpack_right_shift_u8(src_p[3], 2u, 0x0cu);
    dst_p->bms_vcu_wakeup_bms = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->bms_hv_interlock_status = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->bms_onc_con_st = unpack_right_shift_u8(src_p[4], 0u, 0x07u);
    dst_p->bms_vcu_soc = unpack_left_shift_u16(src_p[5], 2u, 0xffu);
    dst_p->bms_vcu_soc |= unpack_right_shift_u16(src_p[6], 6u, 0xc0u);
    dst_p->bms_bool_battbalance_act = unpack_right_shift_u8(src_p[6], 5u, 0x20u);
    dst_p->bms_109_rolling_counter = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->bms_109_checksum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_109_bms_pre_chg_st_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_109_bms_work_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_109_bms_fault_level_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_109_bms_hv_ctrl_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_neg_relay_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_pre_relay_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_pos_relay_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_chg_status_t_box_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_109_bms_s2switch_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_dis_chg_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_109_bms_crash_sig_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_bms_109_bms_chg_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_109_bms_cc2_sta_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_109_bms_vcu_wakeup_bms_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_hv_interlock_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_onc_con_st_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_109_bms_vcu_soc_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

bool e3_bms_109_bms_bool_battbalance_act_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_109_bms_109_rolling_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_bms_109_bms_109_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_bms_357_pack(
    uint8_t *dst_p,
    const struct e3_bms_357_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->bms_max_cell_volt, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->bms_max_cell_volt, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->bms_min_cell_volt, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->bms_min_cell_volt, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_soh, 2u, 0xfcu);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_max_cv_no, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_min_cv_no, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_12_v_volt, 0u, 0xffu);

    return (8);
}

int e3_bms_357_unpack(
    struct e3_bms_357_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_max_cell_volt = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->bms_max_cell_volt |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->bms_min_cell_volt = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->bms_min_cell_volt |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->bms_soh = unpack_right_shift_u8(src_p[4], 2u, 0xfcu);
    dst_p->bms_max_cv_no = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->bms_min_cv_no = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->bms_12_v_volt = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_357_bms_max_cell_volt_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool e3_bms_357_bms_min_cell_volt_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool e3_bms_357_bms_soh_is_in_range(uint8_t value)
{
    return (value <= 20u);
}

bool e3_bms_357_bms_max_cv_no_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_357_bms_min_cv_no_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_357_bms_12_v_volt_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_bms_358_pack(
    uint8_t *dst_p,
    const struct e3_bms_358_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_max_cell_temp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_max_ct_no, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_min_cell_temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_min_ct_no, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_temp_input_act_bat, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_bat_temp_in_desr, 0u, 0xffu);

    return (8);
}

int e3_bms_358_unpack(
    struct e3_bms_358_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_max_cell_temp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_max_ct_no = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->bms_min_cell_temp = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->bms_min_ct_no = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->bms_temp_input_act_bat = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->bms_bat_temp_in_desr = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_358_bms_max_cell_temp_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool e3_bms_358_bms_max_ct_no_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_358_bms_min_cell_temp_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool e3_bms_358_bms_min_ct_no_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_358_bms_temp_input_act_bat_is_in_range(uint8_t value)
{
    return (value <= 254u);
}

bool e3_bms_358_bms_bat_temp_in_desr_is_in_range(uint8_t value)
{
    return (value <= 254u);
}

int e3_bms_360_pack(
    uint8_t *dst_p,
    const struct e3_bms_360_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->bms_chg_req_curr, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->bms_chg_req_curr, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_chg_req_volt, 6u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->bms_chg_req_volt, 2u, 0xfcu);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_ob_cmod_req, 0u, 0x03u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_obc_out_enb, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_dis_chg_limit_curr, 0u, 0x7fu);
    dst_p[4] |= pack_right_shift_u16(src_p->bms_dis_chg_req_volt, 1u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->bms_dis_chg_req_volt, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_dis_chg_allowed_out_pwr, 0u, 0x7fu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_bat_cool_req, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_bat_heat_req, 1u, 0x02u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_chag_lock_request, 0u, 0x01u);

    return (8);
}

int e3_bms_360_unpack(
    struct e3_bms_360_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_chg_req_curr = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->bms_chg_req_curr |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->bms_chg_req_volt = unpack_left_shift_u16(src_p[1], 6u, 0x0fu);
    dst_p->bms_chg_req_volt |= unpack_right_shift_u16(src_p[2], 2u, 0xfcu);
    dst_p->bms_ob_cmod_req = unpack_right_shift_u8(src_p[2], 0u, 0x03u);
    dst_p->bms_obc_out_enb = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->bms_dis_chg_limit_curr = unpack_right_shift_u8(src_p[3], 0u, 0x7fu);
    dst_p->bms_dis_chg_req_volt = unpack_left_shift_u16(src_p[4], 1u, 0xffu);
    dst_p->bms_dis_chg_req_volt |= unpack_right_shift_u16(src_p[5], 7u, 0x80u);
    dst_p->bms_dis_chg_allowed_out_pwr = unpack_right_shift_u8(src_p[5], 0u, 0x7fu);
    dst_p->bms_bat_cool_req = unpack_right_shift_u8(src_p[7], 2u, 0x04u);
    dst_p->bms_bat_heat_req = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
    dst_p->bms_chag_lock_request = unpack_right_shift_u8(src_p[7], 0u, 0x01u);

    return (0);
}

bool e3_bms_360_bms_chg_req_curr_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_bms_360_bms_chg_req_volt_is_in_range(uint16_t value)
{
    return (value <= 800u);
}

bool e3_bms_360_bms_ob_cmod_req_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_360_bms_obc_out_enb_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_360_bms_dis_chg_limit_curr_is_in_range(uint8_t value)
{
    return (value <= 80u);
}

bool e3_bms_360_bms_dis_chg_req_volt_is_in_range(uint16_t value)
{
    return (value <= 400u);
}

bool e3_bms_360_bms_dis_chg_allowed_out_pwr_is_in_range(uint8_t value)
{
    return (value <= 66u);
}

bool e3_bms_360_bms_bat_cool_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_360_bms_bat_heat_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_360_bms_chag_lock_request_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_bms_35_a_pack(
    uint8_t *dst_p,
    const struct e3_bms_35_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->bms_power, 1u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->bms_power, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u16(src_p->bms_chg_amount, 3u, 0x7fu);
    dst_p[2] |= pack_left_shift_u16(src_p->bms_chg_amount, 5u, 0xe0u);
    dst_p[2] |= pack_right_shift_u16(src_p->bms_dis_chg_amount, 5u, 0x1fu);
    dst_p[3] |= pack_left_shift_u16(src_p->bms_dis_chg_amount, 3u, 0xf8u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_charge_status_light_control, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_charge_connect_light_ctr, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_batter_fault_light_control, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_soc_low_light_control, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_batter_higtemp_light_control, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_insulation_fault_light_control, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_chg_finish_remain_time, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_bat_heat_man_mode_acti, 6u, 0xc0u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_chg_finish_remainminute_time, 0u, 0x3fu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_charger_reminder, 0u, 0x01u);

    return (8);
}

int e3_bms_35_a_unpack(
    struct e3_bms_35_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_power = unpack_left_shift_u16(src_p[0], 1u, 0xffu);
    dst_p->bms_power |= unpack_right_shift_u16(src_p[1], 7u, 0x80u);
    dst_p->bms_chg_amount = unpack_left_shift_u16(src_p[1], 3u, 0x7fu);
    dst_p->bms_chg_amount |= unpack_right_shift_u16(src_p[2], 5u, 0xe0u);
    dst_p->bms_dis_chg_amount = unpack_left_shift_u16(src_p[2], 5u, 0x1fu);
    dst_p->bms_dis_chg_amount |= unpack_right_shift_u16(src_p[3], 3u, 0xf8u);
    dst_p->bms_charge_status_light_control = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->bms_charge_connect_light_ctr = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->bms_batter_fault_light_control = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->bms_soc_low_light_control = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->bms_batter_higtemp_light_control = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->bms_insulation_fault_light_control = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->bms_chg_finish_remain_time = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->bms_bat_heat_man_mode_acti = unpack_right_shift_u8(src_p[6], 6u, 0xc0u);
    dst_p->bms_chg_finish_remainminute_time = unpack_right_shift_u8(src_p[6], 0u, 0x3fu);
    dst_p->bms_charger_reminder = unpack_right_shift_u8(src_p[7], 0u, 0x01u);

    return (0);
}

bool e3_bms_35_a_bms_power_is_in_range(uint16_t value)
{
    return (value <= 508u);
}

bool e3_bms_35_a_bms_chg_amount_is_in_range(uint16_t value)
{
    return (value <= 600u);
}

bool e3_bms_35_a_bms_dis_chg_amount_is_in_range(uint16_t value)
{
    return (value <= 600u);
}

bool e3_bms_35_a_bms_charge_status_light_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_35_a_bms_charge_connect_light_ctr_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_35_a_bms_batter_fault_light_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_35_a_bms_soc_low_light_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_35_a_bms_batter_higtemp_light_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_35_a_bms_insulation_fault_light_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_35_a_bms_chg_finish_remain_time_is_in_range(uint8_t value)
{
    return (value <= 254u);
}

bool e3_bms_35_a_bms_bat_heat_man_mode_acti_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_35_a_bms_chg_finish_remainminute_time_is_in_range(uint8_t value)
{
    return (value <= 59u);
}

bool e3_bms_35_a_bms_charger_reminder_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_bms_363_pack(
    uint8_t *dst_p,
    const struct e3_bms_363_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_temp_num, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_temp_no, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_temp_val1, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_temp_val2, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_temp_val3, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_temp_val4, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_temp_val5, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_temp_val6, 0u, 0xffu);

    return (8);
}

int e3_bms_363_unpack(
    struct e3_bms_363_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_temp_num = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_temp_no = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->bms_temp_val1 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->bms_temp_val2 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->bms_temp_val3 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bms_temp_val4 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->bms_temp_val5 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->bms_temp_val6 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_363_bms_temp_num_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_363_bms_temp_no_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_363_bms_temp_val1_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool e3_bms_363_bms_temp_val2_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool e3_bms_363_bms_temp_val3_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool e3_bms_363_bms_temp_val4_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool e3_bms_363_bms_temp_val5_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

bool e3_bms_363_bms_temp_val6_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

int e3_bms_35_f_pack(
    uint8_t *dst_p,
    const struct e3_bms_35_f_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_cell_num, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_cv_no, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->bms_cell_volt1, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->bms_cell_volt1, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->bms_cell_volt2, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->bms_cell_volt2, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->bms_cell_volt3, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->bms_cell_volt3, 0u, 0xffu);

    return (8);
}

int e3_bms_35_f_unpack(
    struct e3_bms_35_f_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_cell_num = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_cv_no = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->bms_cell_volt1 = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->bms_cell_volt1 |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->bms_cell_volt2 = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->bms_cell_volt2 |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->bms_cell_volt3 = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->bms_cell_volt3 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_35_f_bms_cell_num_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_35_f_bms_cv_no_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_35_f_bms_cell_volt1_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool e3_bms_35_f_bms_cell_volt2_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool e3_bms_35_f_bms_cell_volt3_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

int e3_bms_59_b_pack(
    uint8_t *dst_p,
    const struct e3_bms_59_b_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_bat_under_volt, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_bat_over_volt, 4u, 0x30u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_temp_high, 2u, 0x0cu);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_delt_temp_err, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_soc_over_alarm, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_cell_under_volt, 4u, 0x30u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_cell_over_volt, 2u, 0x0cu);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_soc_low, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_insulation_fault_inside, 6u, 0xc0u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_cell_delt_volt_err, 4u, 0x30u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_temp_low, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_chgable_ensys_matc_alarm, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_soc_transit_alarm, 0u, 0x03u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_pos_rly_fault, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_temp_detect_fault, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_curr_detect_fault, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_volt_detect_fault, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_prechg_fault, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_int_com_fault, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_ext_com_fault, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_crash_fault, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_ac_chg_lock_fault, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_veh_enquip_over_alarm, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_prechg_rly_fault, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_neg_rly_fault, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_dc_chg_port_over_temp, 6u, 0xc0u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_insulation_fault_outside, 4u, 0x30u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_cell_volt_detect_fault, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_cc2_fault, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_pack_thermal_runaway_alarm, 3u, 0x08u);

    return (8);
}

int e3_bms_59_b_unpack(
    struct e3_bms_59_b_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_bat_under_volt = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->bms_bat_over_volt = unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->bms_temp_high = unpack_right_shift_u8(src_p[0], 2u, 0x0cu);
    dst_p->bms_delt_temp_err = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->bms_soc_over_alarm = unpack_right_shift_u8(src_p[1], 6u, 0xc0u);
    dst_p->bms_cell_under_volt = unpack_right_shift_u8(src_p[1], 4u, 0x30u);
    dst_p->bms_cell_over_volt = unpack_right_shift_u8(src_p[1], 2u, 0x0cu);
    dst_p->bms_soc_low = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->bms_insulation_fault_inside = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->bms_cell_delt_volt_err = unpack_right_shift_u8(src_p[2], 4u, 0x30u);
    dst_p->bms_temp_low = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->bms_chgable_ensys_matc_alarm = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->bms_soc_transit_alarm = unpack_right_shift_u8(src_p[2], 0u, 0x03u);
    dst_p->bms_pos_rly_fault = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->bms_temp_detect_fault = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->bms_curr_detect_fault = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->bms_volt_detect_fault = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->bms_prechg_fault = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->bms_int_com_fault = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->bms_ext_com_fault = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->bms_crash_fault = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->bms_ac_chg_lock_fault = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->bms_veh_enquip_over_alarm = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->bms_prechg_rly_fault = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->bms_neg_rly_fault = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->bms_dc_chg_port_over_temp = unpack_right_shift_u8(src_p[5], 6u, 0xc0u);
    dst_p->bms_insulation_fault_outside = unpack_right_shift_u8(src_p[5], 4u, 0x30u);
    dst_p->bms_cell_volt_detect_fault = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->bms_cc2_fault = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->bms_pack_thermal_runaway_alarm = unpack_right_shift_u8(src_p[6], 3u, 0x08u);

    return (0);
}

bool e3_bms_59_b_bms_bat_under_volt_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_bat_over_volt_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_temp_high_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_delt_temp_err_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_soc_over_alarm_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_cell_under_volt_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_cell_over_volt_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_soc_low_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_insulation_fault_inside_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_cell_delt_volt_err_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_temp_low_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_chgable_ensys_matc_alarm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_soc_transit_alarm_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_pos_rly_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_temp_detect_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_curr_detect_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_volt_detect_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_prechg_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_int_com_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_ext_com_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_crash_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_ac_chg_lock_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_veh_enquip_over_alarm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_prechg_rly_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_neg_rly_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_dc_chg_port_over_temp_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_insulation_fault_outside_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_59_b_bms_cell_volt_detect_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_cc2_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_59_b_bms_pack_thermal_runaway_alarm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_bms_version_580_pack(
    uint8_t *dst_p,
    const struct e3_bms_version_580_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_curr_detect_temp_fault, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_12_v_over_volt, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_12_v_under_volt, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_obc_fult, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_chg_over_current, 2u, 0x0cu);
    dst_p[0] |= pack_left_shift_u8(src_p->bms_dis_over_current, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_total_fault_num, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_err_num, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_cell_under_volt_level4, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_balanceresist_fault, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_balance_fault, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_temp_waterinput_fault, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_batcool_fault, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_batheat_fault, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_fuse_faullt, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_inspection_fault, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_sum_ah, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->bms_soe, 2u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->bms_soe, 6u, 0xc0u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_temp_detect_fault_level2, 5u, 0x20u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_cell_volt_detect_fault_level2, 4u, 0x10u);

    return (8);
}

int e3_bms_version_580_unpack(
    struct e3_bms_version_580_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_curr_detect_temp_fault = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->bms_12_v_over_volt = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->bms_12_v_under_volt = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->bms_obc_fult = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->bms_chg_over_current = unpack_right_shift_u8(src_p[0], 2u, 0x0cu);
    dst_p->bms_dis_over_current = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->bms_total_fault_num = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->bms_err_num = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->bms_cell_under_volt_level4 = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->bms_balanceresist_fault = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->bms_balance_fault = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->bms_temp_waterinput_fault = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->bms_batcool_fault = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->bms_batheat_fault = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->bms_fuse_faullt = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->bms_inspection_fault = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->bms_sum_ah = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bms_soe = unpack_left_shift_u16(src_p[5], 2u, 0xffu);
    dst_p->bms_soe |= unpack_right_shift_u16(src_p[6], 6u, 0xc0u);
    dst_p->bms_temp_detect_fault_level2 = unpack_right_shift_u8(src_p[6], 5u, 0x20u);
    dst_p->bms_cell_volt_detect_fault_level2 = unpack_right_shift_u8(src_p[6], 4u, 0x10u);

    return (0);
}

bool e3_bms_version_580_bms_curr_detect_temp_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_12_v_over_volt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_12_v_under_volt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_obc_fult_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_chg_over_current_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_version_580_bms_dis_over_current_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_bms_version_580_bms_total_fault_num_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_version_580_bms_err_num_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_version_580_bms_cell_under_volt_level4_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_balanceresist_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_balance_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_temp_waterinput_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_batcool_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_batheat_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_fuse_faullt_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_inspection_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_sum_ah_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_version_580_bms_soe_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

bool e3_bms_version_580_bms_temp_detect_fault_level2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_580_bms_cell_volt_detect_fault_level2_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_bms_version_581_pack(
    uint8_t *dst_p,
    const struct e3_bms_version_581_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_cv_no1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_1_cell_balance_sts, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_2_cell_balance_sts, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_3_cell_balance_sts, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_4_cell_balance_sts, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_5_cell_balance_sts, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_6_cell_balance_sts, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_7_cell_balance_sts, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_8_cell_balance_sts, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_9_cell_balance_sts, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_10_cell_balance_sts, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_11_cell_balance_sts, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_12_cell_balance_sts, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_13_cell_balance_sts, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_14_cell_balance_sts, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_15_cell_balance_sts, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_16_cell_balance_sts, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_17_cell_balance_sts, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_18_cell_balance_sts, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_19_cell_balance_sts, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_20_cell_balance_sts, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_21_cell_balance_sts, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_22_cell_balance_sts, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_23_cell_balance_sts, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_24_cell_balance_sts, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_25_cell_balance_sts, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_26_cell_balance_sts, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_27_cell_balance_sts, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_28_cell_balance_sts, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_29_cell_balance_sts, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_30_cell_balance_sts, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_31_cell_balance_sts, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_32_cell_balance_sts, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_33_cell_balance_sts, 7u, 0x80u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_34_cell_balance_sts, 6u, 0x40u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_35_cell_balance_sts, 5u, 0x20u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_36_cell_balance_sts, 4u, 0x10u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_37_cell_balance_sts, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_38_cell_balance_sts, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_39_cell_balance_sts, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_40_cell_balance_sts, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_41_cell_balance_sts, 7u, 0x80u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_42_cell_balance_sts, 6u, 0x40u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_43_cell_balance_sts, 5u, 0x20u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_44_cell_balance_sts, 4u, 0x10u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_45_cell_balance_sts, 3u, 0x08u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_46_cell_balance_sts, 2u, 0x04u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_47_cell_balance_sts, 1u, 0x02u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_48_cell_balance_sts, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_49_cell_balance_sts, 7u, 0x80u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_50_cell_balance_sts, 6u, 0x40u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_51_cell_balance_sts, 5u, 0x20u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_52_cell_balance_sts, 4u, 0x10u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_53_cell_balance_sts, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_54_cell_balance_sts, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_55_cell_balance_sts, 1u, 0x02u);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_56_cell_balance_sts, 0u, 0x01u);

    return (8);
}

int e3_bms_version_581_unpack(
    struct e3_bms_version_581_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_cv_no1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_1_cell_balance_sts = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->bms_2_cell_balance_sts = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->bms_3_cell_balance_sts = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->bms_4_cell_balance_sts = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->bms_5_cell_balance_sts = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->bms_6_cell_balance_sts = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->bms_7_cell_balance_sts = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->bms_8_cell_balance_sts = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->bms_9_cell_balance_sts = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->bms_10_cell_balance_sts = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->bms_11_cell_balance_sts = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->bms_12_cell_balance_sts = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->bms_13_cell_balance_sts = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->bms_14_cell_balance_sts = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->bms_15_cell_balance_sts = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->bms_16_cell_balance_sts = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->bms_17_cell_balance_sts = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->bms_18_cell_balance_sts = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->bms_19_cell_balance_sts = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->bms_20_cell_balance_sts = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->bms_21_cell_balance_sts = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->bms_22_cell_balance_sts = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->bms_23_cell_balance_sts = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->bms_24_cell_balance_sts = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->bms_25_cell_balance_sts = unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    dst_p->bms_26_cell_balance_sts = unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->bms_27_cell_balance_sts = unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->bms_28_cell_balance_sts = unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->bms_29_cell_balance_sts = unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->bms_30_cell_balance_sts = unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->bms_31_cell_balance_sts = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->bms_32_cell_balance_sts = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->bms_33_cell_balance_sts = unpack_right_shift_u8(src_p[5], 7u, 0x80u);
    dst_p->bms_34_cell_balance_sts = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
    dst_p->bms_35_cell_balance_sts = unpack_right_shift_u8(src_p[5], 5u, 0x20u);
    dst_p->bms_36_cell_balance_sts = unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    dst_p->bms_37_cell_balance_sts = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->bms_38_cell_balance_sts = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->bms_39_cell_balance_sts = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->bms_40_cell_balance_sts = unpack_right_shift_u8(src_p[5], 0u, 0x01u);
    dst_p->bms_41_cell_balance_sts = unpack_right_shift_u8(src_p[6], 7u, 0x80u);
    dst_p->bms_42_cell_balance_sts = unpack_right_shift_u8(src_p[6], 6u, 0x40u);
    dst_p->bms_43_cell_balance_sts = unpack_right_shift_u8(src_p[6], 5u, 0x20u);
    dst_p->bms_44_cell_balance_sts = unpack_right_shift_u8(src_p[6], 4u, 0x10u);
    dst_p->bms_45_cell_balance_sts = unpack_right_shift_u8(src_p[6], 3u, 0x08u);
    dst_p->bms_46_cell_balance_sts = unpack_right_shift_u8(src_p[6], 2u, 0x04u);
    dst_p->bms_47_cell_balance_sts = unpack_right_shift_u8(src_p[6], 1u, 0x02u);
    dst_p->bms_48_cell_balance_sts = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->bms_49_cell_balance_sts = unpack_right_shift_u8(src_p[7], 7u, 0x80u);
    dst_p->bms_50_cell_balance_sts = unpack_right_shift_u8(src_p[7], 6u, 0x40u);
    dst_p->bms_51_cell_balance_sts = unpack_right_shift_u8(src_p[7], 5u, 0x20u);
    dst_p->bms_52_cell_balance_sts = unpack_right_shift_u8(src_p[7], 4u, 0x10u);
    dst_p->bms_53_cell_balance_sts = unpack_right_shift_u8(src_p[7], 3u, 0x08u);
    dst_p->bms_54_cell_balance_sts = unpack_right_shift_u8(src_p[7], 2u, 0x04u);
    dst_p->bms_55_cell_balance_sts = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
    dst_p->bms_56_cell_balance_sts = unpack_right_shift_u8(src_p[7], 0u, 0x01u);

    return (0);
}

bool e3_bms_version_581_bms_cv_no1_is_in_range(uint8_t value)
{
    return (value <= 249u);
}

bool e3_bms_version_581_bms_1_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_2_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_3_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_4_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_5_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_6_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_7_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_8_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_9_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_10_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_11_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_12_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_13_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_14_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_15_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_16_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_17_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_18_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_19_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_20_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_21_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_22_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_23_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_24_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_25_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_26_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_27_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_28_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_29_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_30_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_31_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_32_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_33_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_34_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_35_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_36_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_37_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_38_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_39_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_40_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_41_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_42_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_43_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_44_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_45_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_46_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_47_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_48_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_49_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_50_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_51_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_52_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_53_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_54_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_55_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bms_version_581_bms_56_cell_balance_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_bms_version_3_e1_pack(
    uint8_t *dst_p,
    const struct e3_bms_version_3_e1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->bmsh_request_dc_charge_limit_voltage, 1u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->bmsh_request_dc_charge_limit_voltage, 7u, 0x80u);
    dst_p[1] |= pack_right_shift_u16(src_p->dc_equipment_display_voltage, 2u, 0x7fu);
    dst_p[2] |= pack_left_shift_u16(src_p->dc_equipment_display_voltage, 6u, 0xc0u);
    dst_p[4] |= pack_left_shift_u8(src_p->bmsh_request_dc_charge_current, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->dc_equipment_display_current, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->bms_ins_res_val_inside, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->bms_ins_res_val_inside, 0u, 0xffu);

    return (8);
}

int e3_bms_version_3_e1_unpack(
    struct e3_bms_version_3_e1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bmsh_request_dc_charge_limit_voltage = unpack_left_shift_u16(src_p[0], 1u, 0xffu);
    dst_p->bmsh_request_dc_charge_limit_voltage |= unpack_right_shift_u16(src_p[1], 7u, 0x80u);
    dst_p->dc_equipment_display_voltage = unpack_left_shift_u16(src_p[1], 2u, 0x7fu);
    dst_p->dc_equipment_display_voltage |= unpack_right_shift_u16(src_p[2], 6u, 0xc0u);
    dst_p->bmsh_request_dc_charge_current = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->dc_equipment_display_current = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->bms_ins_res_val_inside = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->bms_ins_res_val_inside |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_version_3_e1_bmsh_request_dc_charge_limit_voltage_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

bool e3_bms_version_3_e1_dc_equipment_display_voltage_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

bool e3_bms_version_3_e1_bmsh_request_dc_charge_current_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_version_3_e1_dc_equipment_display_current_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_version_3_e1_bms_ins_res_val_inside_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

int e3_bms_59_d_pack(
    uint8_t *dst_p,
    const struct e3_bms_59_d_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_lehth, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_lehth_code, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_n, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_n_1, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_n_2, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_n_3, 0u, 0xffu);

    return (8);
}

int e3_bms_59_d_unpack(
    struct e3_bms_59_d_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_avai_chg_sys_nums = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_lehth = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_lehth_code = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_n = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_n_1 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_n_2 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_n_3 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

bool e3_bms_59_d_bms_avai_chg_sys_nums_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_d_bms_avai_chg_sys_nums_lehth_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 50u));
}

bool e3_bms_59_d_bms_avai_chg_sys_nums_lehth_code_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 50u));
}

bool e3_bms_59_d_bms_avai_chg_sys_nums_n_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_59_d_bms_avai_chg_sys_nums_n_1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_59_d_bms_avai_chg_sys_nums_n_2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_59_d_bms_avai_chg_sys_nums_n_3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_bms_gbt32960_59_a_pack(
    uint8_t *dst_p,
    const struct e3_bms_gbt32960_59_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_dtc_counter, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->bms_dtc_list, 24u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->bms_dtc_list, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->bms_dtc_list, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->bms_dtc_list, 0u, 0xffu);

    return (8);
}

int e3_bms_gbt32960_59_a_unpack(
    struct e3_bms_gbt32960_59_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_dtc_counter = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_dtc_list = unpack_left_shift_u32(src_p[1], 24u, 0xffu);
    dst_p->bms_dtc_list |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->bms_dtc_list |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->bms_dtc_list |= unpack_right_shift_u32(src_p[4], 0u, 0xffu);

    return (0);
}

bool e3_bms_gbt32960_59_a_bms_dtc_counter_is_in_range(uint8_t value)
{
    return (value <= 252u);
}

bool e3_bms_gbt32960_59_a_bms_dtc_list_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int e3_bms_59_e_pack(
    uint8_t *dst_p,
    const struct e3_bms_59_e_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_bat_subsys_max_volt, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->bms_bat_subsys_min_volt, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->bms_subsys_max_temp, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->bms_subsys_min_temp, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_volt, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_number_volt, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_nums_temp, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->bms_avai_chg_sys_number_temp, 0u, 0xffu);

    return (8);
}

int e3_bms_59_e_unpack(
    struct e3_bms_59_e_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_bat_subsys_max_volt = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_bat_subsys_min_volt = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->bms_subsys_max_temp = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->bms_subsys_min_temp = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_volt = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_number_volt = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_nums_temp = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->bms_avai_chg_sys_number_temp = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_59_e_bms_bat_subsys_max_volt_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_e_bms_bat_subsys_min_volt_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_e_bms_subsys_max_temp_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_e_bms_subsys_min_temp_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_e_bms_avai_chg_sys_nums_volt_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_e_bms_avai_chg_sys_number_volt_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_e_bms_avai_chg_sys_nums_temp_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

bool e3_bms_59_e_bms_avai_chg_sys_number_temp_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 250u));
}

int e3_bms_test_version_69_c_pack(
    uint8_t *dst_p,
    const struct e3_bms_test_version_69_c_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_hw_version_sign, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->bms_hw_version, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->bms_hw_version, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->bms_hw_version, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bms_sw_version_sign, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->bms_sw_version, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->bms_sw_version, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(src_p->bms_sw_version, 0u, 0xffu);

    return (8);
}

int e3_bms_test_version_69_c_unpack(
    struct e3_bms_test_version_69_c_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_hw_version_sign = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bms_hw_version = unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    dst_p->bms_hw_version |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->bms_hw_version |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->bms_sw_version_sign = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bms_sw_version = unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->bms_sw_version |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    dst_p->bms_sw_version |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_bms_test_version_69_c_bms_hw_version_sign_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_test_version_69_c_bms_hw_version_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

bool e3_bms_test_version_69_c_bms_sw_version_sign_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_bms_test_version_69_c_bms_sw_version_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

int e3_bms_version_3_e4_pack(
    uint8_t *dst_p,
    const struct e3_bms_version_3_e4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bms_heat_disp, 2u, 0x1cu);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_dc_chg_disp, 3u, 0x38u);
    dst_p[5] |= pack_left_shift_u8(src_p->bms_ac_chg_disp, 0u, 0x07u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_dis_chg_disp, 5u, 0xe0u);
    dst_p[6] |= pack_left_shift_u8(src_p->bms_int_chg_disp, 2u, 0x1cu);

    return (8);
}

int e3_bms_version_3_e4_unpack(
    struct e3_bms_version_3_e4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bms_heat_disp = unpack_right_shift_u8(src_p[0], 2u, 0x1cu);
    dst_p->bms_dc_chg_disp = unpack_right_shift_u8(src_p[5], 3u, 0x38u);
    dst_p->bms_ac_chg_disp = unpack_right_shift_u8(src_p[5], 0u, 0x07u);
    dst_p->bms_dis_chg_disp = unpack_right_shift_u8(src_p[6], 5u, 0xe0u);
    dst_p->bms_int_chg_disp = unpack_right_shift_u8(src_p[6], 2u, 0x1cu);

    return (0);
}

bool e3_bms_version_3_e4_bms_heat_disp_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_version_3_e4_bms_dc_chg_disp_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_version_3_e4_bms_ac_chg_disp_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_version_3_e4_bms_dis_chg_disp_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bms_version_3_e4_bms_int_chg_disp_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int e3_mcuf0_state_112_pack(
    uint8_t *dst_p,
    const struct e3_mcuf0_state_112_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_right_shift_u16(src_p->mcuf0_i_bus, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->mcuf0_i_bus, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->mcuf0_v_bus, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->mcuf0_v_bus, 0u, 0xffu);

    return (8);
}

int e3_mcuf0_state_112_unpack(
    struct e3_mcuf0_state_112_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mcuf0_i_bus = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->mcuf0_i_bus |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->mcuf0_v_bus = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->mcuf0_v_bus |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

bool e3_mcuf0_state_112_mcuf0_i_bus_is_in_range(uint16_t value)
{
    return (value <= 20000u);
}

bool e3_mcuf0_state_112_mcuf0_v_bus_is_in_range(uint16_t value)
{
    return (value <= 60000u);
}

int e3_vcu_253_pack(
    uint8_t *dst_p,
    const struct e3_vcu_253_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->hv_bat_power_enable, 1u, 0x06u);
    dst_p[1] |= pack_left_shift_u8(src_p->vehicle_charge_state, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->vehicle_discharging_state, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->vcu_chg_pos_relay_st, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->vcu_chg_neg_relay_st, 4u, 0x10u);
    dst_p[3] |= pack_right_shift_u8(src_p->hv_net_cosumption_power, 3u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->hv_net_cosumption_power, 5u, 0xe0u);
    dst_p[4] |= pack_left_shift_u8(src_p->allow_int_chg_state, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->vcu_253_message_counter, 4u, 0xf0u);
    dst_p[7] |= pack_left_shift_u8(src_p->vcu_253_check_sum, 0u, 0xffu);

    return (8);
}

int e3_vcu_253_unpack(
    struct e3_vcu_253_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->hv_bat_power_enable = unpack_right_shift_u8(src_p[1], 1u, 0x06u);
    dst_p->vehicle_charge_state = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->vehicle_discharging_state = unpack_right_shift_u8(src_p[2], 4u, 0x10u);
    dst_p->vcu_chg_pos_relay_st = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->vcu_chg_neg_relay_st = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->hv_net_cosumption_power = unpack_left_shift_u8(src_p[3], 3u, 0x0fu);
    dst_p->hv_net_cosumption_power |= unpack_right_shift_u8(src_p[4], 5u, 0xe0u);
    dst_p->allow_int_chg_state = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->vcu_253_message_counter = unpack_right_shift_u8(src_p[6], 4u, 0xf0u);
    dst_p->vcu_253_check_sum = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_vcu_253_hv_bat_power_enable_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_vcu_253_vehicle_charge_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_vcu_253_vehicle_discharging_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_vcu_253_vcu_chg_pos_relay_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_vcu_253_vcu_chg_neg_relay_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_vcu_253_hv_net_cosumption_power_is_in_range(uint8_t value)
{
    return (value <= 66u);
}

bool e3_vcu_253_allow_int_chg_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_vcu_253_vcu_253_message_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_vcu_253_vcu_253_check_sum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_obc_state1_387_pack(
    uint8_t *dst_p,
    const struct e3_obc_state1_387_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->obc_dc_current, 5u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->obc_dc_current, 3u, 0xf8u);
    dst_p[1] |= pack_right_shift_u16(src_p->obc_dc_voltage, 8u, 0x03u);
    dst_p[2] |= pack_left_shift_u16(src_p->obc_dc_voltage, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->obc_workstate, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->obc_work_mode, 4u, 0x30u);
    dst_p[3] |= pack_right_shift_u16(src_p->obc_limit_current, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->obc_limit_current, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->obc_temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->obc_limit_power, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->obc_bms_conmin_fault, 4u, 0x10u);

    return (8);
}

int e3_obc_state1_387_unpack(
    struct e3_obc_state1_387_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->obc_dc_current = unpack_left_shift_u16(src_p[0], 5u, 0xffu);
    dst_p->obc_dc_current |= unpack_right_shift_u16(src_p[1], 3u, 0xf8u);
    dst_p->obc_dc_voltage = unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->obc_dc_voltage |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->obc_workstate = unpack_right_shift_u8(src_p[3], 6u, 0xc0u);
    dst_p->obc_work_mode = unpack_right_shift_u8(src_p[3], 4u, 0x30u);
    dst_p->obc_limit_current = unpack_left_shift_u16(src_p[3], 8u, 0x0fu);
    dst_p->obc_limit_current |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->obc_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->obc_limit_power = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->obc_bms_conmin_fault = unpack_right_shift_u8(src_p[7], 4u, 0x10u);

    return (0);
}

bool e3_obc_state1_387_obc_dc_current_is_in_range(uint16_t value)
{
    return (value <= 2000u);
}

bool e3_obc_state1_387_obc_dc_voltage_is_in_range(uint16_t value)
{
    return (value <= 800u);
}

bool e3_obc_state1_387_obc_workstate_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_obc_state1_387_obc_work_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_obc_state1_387_obc_limit_current_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_obc_state1_387_obc_temp_is_in_range(uint8_t value)
{
    return (value <= 254u);
}

bool e3_obc_state1_387_obc_limit_power_is_in_range(uint8_t value)
{
    return (value <= 240u);
}

bool e3_obc_state1_387_obc_bms_conmin_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_obc_state2_388_pack(
    uint8_t *dst_p,
    const struct e3_obc_state2_388_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->obc_ac_current, 4u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->obc_ac_current, 4u, 0xf0u);
    dst_p[1] |= pack_right_shift_u16(src_p->obc_ac_voltage, 8u, 0x03u);
    dst_p[2] |= pack_left_shift_u16(src_p->obc_ac_voltage, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->obc_fault_level, 5u, 0xe0u);
    dst_p[3] |= pack_left_shift_u8(src_p->obc_bat_connect_state, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->obc_ac_input_fault_state, 2u, 0x0cu);
    dst_p[4] |= pack_left_shift_u8(src_p->obc_inlet_temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->obc_a_ccharge_port_temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->obc_cc_status, 6u, 0x40u);
    dst_p[6] |= pack_left_shift_u8(src_p->obc_cp_status, 5u, 0x20u);
    dst_p[6] |= pack_left_shift_u8(src_p->obc_s2_switch_status, 4u, 0x10u);
    dst_p[6] |= pack_left_shift_u8(src_p->obc_dtc_num, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->obc_dtc_list, 0u, 0xffu);

    return (8);
}

int e3_obc_state2_388_unpack(
    struct e3_obc_state2_388_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->obc_ac_current = unpack_left_shift_u16(src_p[0], 4u, 0xffu);
    dst_p->obc_ac_current |= unpack_right_shift_u16(src_p[1], 4u, 0xf0u);
    dst_p->obc_ac_voltage = unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->obc_ac_voltage |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->obc_fault_level = unpack_right_shift_u8(src_p[3], 5u, 0xe0u);
    dst_p->obc_bat_connect_state = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->obc_ac_input_fault_state = unpack_right_shift_u8(src_p[3], 2u, 0x0cu);
    dst_p->obc_inlet_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->obc_a_ccharge_port_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->obc_cc_status = unpack_right_shift_u8(src_p[6], 6u, 0x40u);
    dst_p->obc_cp_status = unpack_right_shift_u8(src_p[6], 5u, 0x20u);
    dst_p->obc_s2_switch_status = unpack_right_shift_u8(src_p[6], 4u, 0x10u);
    dst_p->obc_dtc_num = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->obc_dtc_list = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

bool e3_obc_state2_388_obc_ac_current_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool e3_obc_state2_388_obc_ac_voltage_is_in_range(uint16_t value)
{
    return (value <= 800u);
}

bool e3_obc_state2_388_obc_fault_level_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_obc_state2_388_obc_bat_connect_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_obc_state2_388_obc_ac_input_fault_state_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_obc_state2_388_obc_inlet_temp_is_in_range(uint8_t value)
{
    return (value <= 254u);
}

bool e3_obc_state2_388_obc_a_ccharge_port_temp_is_in_range(uint8_t value)
{
    return (value <= 254u);
}

bool e3_obc_state2_388_obc_cc_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_obc_state2_388_obc_cp_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_obc_state2_388_obc_s2_switch_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_obc_state2_388_obc_dtc_num_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_obc_state2_388_obc_dtc_list_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int e3_obc_state3_389_pack(
    uint8_t *dst_p,
    const struct e3_obc_state3_389_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->obc_cc_res, 8u, 0x7fu);
    dst_p[1] |= pack_left_shift_u16(src_p->obc_cc_res, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->obc_cp_duty, 1u, 0xfeu);
    dst_p[3] |= pack_left_shift_u8(src_p->obc_system_status, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->obc_ratio, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->obc_interlock_fault, 7u, 0x80u);

    return (8);
}

int e3_obc_state3_389_unpack(
    struct e3_obc_state3_389_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->obc_cc_res = unpack_left_shift_u16(src_p[0], 8u, 0x7fu);
    dst_p->obc_cc_res |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->obc_cp_duty = unpack_right_shift_u8(src_p[2], 1u, 0xfeu);
    dst_p->obc_system_status = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->obc_ratio = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->obc_interlock_fault = unpack_right_shift_u8(src_p[7], 7u, 0x80u);

    return (0);
}

bool e3_obc_state3_389_obc_cc_res_is_in_range(uint16_t value)
{
    return (value <= 10000u);
}

bool e3_obc_state3_389_obc_cp_duty_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool e3_obc_state3_389_obc_system_status_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_obc_state3_389_obc_ratio_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_obc_state3_389_obc_interlock_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_vcu_335_pack(
    uint8_t *dst_p,
    const struct e3_vcu_335_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->vcu_mode, 0u, 0x0fu);

    return (8);
}

int e3_vcu_335_unpack(
    struct e3_vcu_335_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vcu_mode = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);

    return (0);
}

bool e3_vcu_335_vcu_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int e3_ccu_369_pack(
    uint8_t *dst_p,
    const struct e3_ccu_369_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[5] |= pack_left_shift_u8(src_p->compressor_state, 5u, 0xe0u);

    return (8);
}

int e3_ccu_369_unpack(
    struct e3_ccu_369_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->compressor_state = unpack_right_shift_u8(src_p[5], 5u, 0xe0u);

    return (0);
}

bool e3_ccu_369_compressor_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int e3_ptch_379_pack(
    uint8_t *dst_p,
    const struct e3_ptch_379_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ptc_power_rate, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->tempreture_of_out_water, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->tempreture_of_ptc, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->ptc_work_current, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->hv_voltage, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->run_status, 6u, 0xc0u);
    dst_p[5] |= pack_left_shift_u8(src_p->error_code, 3u, 0x38u);

    return (8);
}

int e3_ptch_379_unpack(
    struct e3_ptch_379_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ptc_power_rate = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->tempreture_of_out_water = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->tempreture_of_ptc = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->ptc_work_current = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->hv_voltage = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->run_status = unpack_right_shift_u8(src_p[5], 6u, 0xc0u);
    dst_p->error_code = unpack_right_shift_u8(src_p[5], 3u, 0x38u);

    return (0);
}

bool e3_ptch_379_ptc_power_rate_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_ptch_379_tempreture_of_out_water_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_ptch_379_tempreture_of_ptc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_ptch_379_ptc_work_current_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool e3_ptch_379_hv_voltage_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_ptch_379_run_status_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

bool e3_ptch_379_error_code_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int e3_hmc_36_c_pack(
    uint8_t *dst_p,
    const struct e3_hmc_36_c_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->motor_cool_qualifier, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->vehicle_heat_management_modes, 4u, 0xf0u);
    dst_p[6] |= pack_left_shift_u8(src_p->hmc_36_c_message_counter, 4u, 0xf0u);
    dst_p[6] |= pack_left_shift_u8(src_p->deforest_qualifier, 0u, 0x01u);

    return (8);
}

int e3_hmc_36_c_unpack(
    struct e3_hmc_36_c_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->motor_cool_qualifier = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->vehicle_heat_management_modes = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->hmc_36_c_message_counter = unpack_right_shift_u8(src_p[6], 4u, 0xf0u);
    dst_p->deforest_qualifier = unpack_right_shift_u8(src_p[6], 0u, 0x01u);

    return (0);
}

bool e3_hmc_36_c_motor_cool_qualifier_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_hmc_36_c_vehicle_heat_management_modes_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_hmc_36_c_hmc_36_c_message_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool e3_hmc_36_c_deforest_qualifier_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int e3_hmc_36_d_pack(
    uint8_t *dst_p,
    const struct e3_hmc_36_d_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[3] |= pack_left_shift_u8(src_p->hmc_act_power, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->hmc_work_status, 0u, 0x03u);

    return (8);
}

int e3_hmc_36_d_unpack(
    struct e3_hmc_36_d_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->hmc_act_power = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->hmc_work_status = unpack_right_shift_u8(src_p[6], 0u, 0x03u);

    return (0);
}

bool e3_hmc_36_d_hmc_act_power_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool e3_hmc_36_d_hmc_work_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int e3_abm_385_pack(
    uint8_t *dst_p,
    const struct e3_abm_385_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->abm_crash_output_status, 4u, 0x30u);
    dst_p[0] |= pack_left_shift_u8(src_p->abm_crash_status, 2u, 0x0cu);

    return (8);
}

int e3_abm_385_unpack(
    struct e3_abm_385_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->abm_crash_output_status = unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->abm_crash_status = unpack_right_shift_u8(src_p[0], 2u, 0x0cu);

    return (0);
}

bool e3_abm_385_abm_crash_output_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool e3_abm_385_abm_crash_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int e3_bcm_peps_365_pack(
    uint8_t *dst_p,
    const struct e3_bcm_peps_365_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->ignition_sts, 0u, 0x07u);
    dst_p[4] |= pack_left_shift_u8(src_p->ac_chg_unlock_req, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->ac_chg_status, 6u, 0xc0u);

    return (8);
}

int e3_bcm_peps_365_unpack(
    struct e3_bcm_peps_365_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ignition_sts = unpack_right_shift_u8(src_p[1], 0u, 0x07u);
    dst_p->ac_chg_unlock_req = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->ac_chg_status = unpack_right_shift_u8(src_p[5], 6u, 0xc0u);

    return (0);
}

bool e3_bcm_peps_365_ignition_sts_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool e3_bcm_peps_365_ac_chg_unlock_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool e3_bcm_peps_365_ac_chg_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}
