/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.0.0 Tue Nov  1 13:51:35 2022.
 */

#include <string.h>

#include "hallsensor.h"

static  uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static  uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static  uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static  uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static  uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static  uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int hallsensor_cab500_ip_pack(
    uint8_t *dst_p,
    const struct hallsensor_cab500_ip_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u32(src_p->ip_value, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->ip_value, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->ip_value, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->ip_value, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->error_info, 1u, 0xfeu);
    dst_p[4] |= pack_left_shift_u8(src_p->error_indication, 0u, 0x01u);
    dst_p[5] |= pack_right_shift_u32(src_p->sensor_name, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->sensor_name, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u32(src_p->sensor_name, 0u, 0xffu);

    return (8);
}

int hallsensor_cab500_ip_unpack(
    struct hallsensor_cab500_ip_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ip_value = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    dst_p->ip_value |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    dst_p->ip_value |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->ip_value |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->error_info = unpack_right_shift_u8(src_p[4], 1u, 0xfeu);
    dst_p->error_indication = unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->sensor_name = unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->sensor_name |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
    dst_p->sensor_name |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);

    return (0);
}

uint32_t hallsensor_cab500_ip_ip_value_encode(int value)
{
    return (uint32_t)(value);
}

int hallsensor_cab500_ip_ip_value_decode(uint32_t value)
{
    return ((int)value);
}

bool hallsensor_cab500_ip_ip_value_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t hallsensor_cab500_ip_error_info_encode(int value)
{
    return (uint8_t)(value);
}

int hallsensor_cab500_ip_error_info_decode(uint8_t value)
{
    return ((int)value);
}

bool hallsensor_cab500_ip_error_info_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t hallsensor_cab500_ip_error_indication_encode(int value)
{
    return (uint8_t)(value);
}

int hallsensor_cab500_ip_error_indication_decode(uint8_t value)
{
    return ((int)value);
}

bool hallsensor_cab500_ip_error_indication_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint32_t hallsensor_cab500_ip_sensor_name_encode(int value)
{
    return (uint32_t)(value);
}

int hallsensor_cab500_ip_sensor_name_decode(uint32_t value)
{
    return ((int)value);
}

bool hallsensor_cab500_ip_sensor_name_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}
