/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.0.0 Mon Jul 17 19:43:27 2023.
 */

#include <string.h>

#include "v2.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int v2_msg_response_pack(
    uint8_t *dst_p,
    const struct v2_msg_response_t *src_p,
    size_t size)
{
    uint8_t bitmask_occurred_mea_err;
    uint8_t occurred_measurement_error_1;
    uint8_t occurred_measurement_error_2;
    uint8_t response_id;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    response_id = (uint8_t)src_p->response_id;
    dst_p[0] |= pack_left_shift_u8(response_id, 0u, 0xffu);
    bitmask_occurred_mea_err = (uint8_t)src_p->bitmask_occurred_mea_err;
    dst_p[1] |= pack_left_shift_u8(bitmask_occurred_mea_err, 0u, 0xffu);
    occurred_measurement_error_1 = (uint8_t)src_p->occurred_measurement_error_1;
    dst_p[2] |= pack_left_shift_u8(occurred_measurement_error_1, 0u, 0xffu);
    occurred_measurement_error_2 = (uint8_t)src_p->occurred_measurement_error_2;
    dst_p[3] |= pack_left_shift_u8(occurred_measurement_error_2, 0u, 0xffu);

    return (8);
}

int v2_msg_response_unpack(
    struct v2_msg_response_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t bitmask_occurred_mea_err;
    uint8_t occurred_measurement_error_1;
    uint8_t occurred_measurement_error_2;
    uint8_t response_id;

    if (size < 8u) {
        return (-EINVAL);
    }

    response_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->response_id = (int8_t)response_id;
    bitmask_occurred_mea_err = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->bitmask_occurred_mea_err = (int8_t)bitmask_occurred_mea_err;
    occurred_measurement_error_1 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->occurred_measurement_error_1 = (int8_t)occurred_measurement_error_1;
    occurred_measurement_error_2 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->occurred_measurement_error_2 = (int8_t)occurred_measurement_error_2;

    return (0);
}

int v2_msg_response_init(struct v2_msg_response_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_msg_response_t));

    return 0;
}

bool v2_msg_response_response_id_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

bool v2_msg_response_bitmask_occurred_mea_err_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

bool v2_msg_response_occurred_measurement_error_1_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

bool v2_msg_response_occurred_measurement_error_2_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int v2_msg_command_pack(
    uint8_t *dst_p,
    const struct v2_msg_command_t *src_p,
    size_t size)
{
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    return (8);
}

int v2_msg_command_unpack(
    struct v2_msg_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    (void)dst_p;
    (void)src_p;

    if (size < 8u) {
        return (-EINVAL);
    }

    return (0);
}

int v2_msg_command_init(struct v2_msg_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_msg_command_t));

    return 0;
}

int v2_msg_result_temperature_pack(
    uint8_t *dst_p,
    const struct v2_msg_result_temperature_t *src_p,
    size_t size)
{
    uint32_t temperature_result;
    uint8_t message_count;
    uint8_t result_state;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->result_id, 0u, 0xffu);
    result_state = (uint8_t)src_p->result_state;
    dst_p[1] |= pack_left_shift_u8(result_state, 4u, 0xf0u);
    message_count = (uint8_t)src_p->message_count;
    dst_p[1] |= pack_left_shift_u8(message_count, 0u, 0x0fu);
    temperature_result = (uint32_t)src_p->temperature_result;
    dst_p[2] |= pack_right_shift_u32(temperature_result, 24u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(temperature_result, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(temperature_result, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(temperature_result, 0u, 0xffu);

    return (6);
}

int v2_msg_result_temperature_unpack(
    struct v2_msg_result_temperature_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t temperature_result;
    uint8_t message_count;
    uint8_t result_state;

    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->result_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    result_state = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);

    if ((result_state & (1u << 3)) != 0u) {
        result_state |= 0xf0u;
    }

    dst_p->result_state = (int8_t)result_state;
    message_count = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);

    if ((message_count & (1u << 3)) != 0u) {
        message_count |= 0xf0u;
    }

    dst_p->message_count = (int8_t)message_count;
    temperature_result = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
    temperature_result |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    temperature_result |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    temperature_result |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    dst_p->temperature_result = (int32_t)temperature_result;

    return (0);
}

int v2_msg_result_temperature_init(struct v2_msg_result_temperature_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_msg_result_temperature_t));

    return 0;
}

bool v2_msg_result_temperature_result_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_msg_result_temperature_result_state_is_in_range(int8_t value)
{
    return ((value >= -8) && (value <= 7));
}

bool v2_msg_result_temperature_message_count_is_in_range(int8_t value)
{
    return ((value >= -8) && (value <= 7));
}

bool v2_msg_result_temperature_temperature_result_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int v2_msg_result_current_shunt_pack(
    uint8_t *dst_p,
    const struct v2_msg_result_current_shunt_t *src_p,
    size_t size)
{
    uint32_t current_result;
    uint8_t message_count;
    uint8_t result_state;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->mux_id, 0u, 0xffu);
    message_count = (uint8_t)src_p->message_count;
    dst_p[1] |= pack_left_shift_u8(message_count, 4u, 0xf0u);
    result_state = (uint8_t)src_p->result_state;
    dst_p[1] |= pack_left_shift_u8(result_state, 0u, 0x0fu);
    current_result = (uint32_t)src_p->current_result;
    dst_p[2] |= pack_right_shift_u32(current_result, 24u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(current_result, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(current_result, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(current_result, 0u, 0xffu);

    return (6);
}

int v2_msg_result_current_shunt_unpack(
    struct v2_msg_result_current_shunt_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t current_result;
    uint8_t message_count;
    uint8_t result_state;

    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->mux_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    message_count = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);

    if ((message_count & (1u << 3)) != 0u) {
        message_count |= 0xf0u;
    }

    dst_p->message_count = (int8_t)message_count;
    result_state = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);

    if ((result_state & (1u << 3)) != 0u) {
        result_state |= 0xf0u;
    }

    dst_p->result_state = (int8_t)result_state;
    current_result = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
    current_result |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    current_result |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    current_result |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    dst_p->current_result = (int32_t)current_result;

    return (0);
}

int v2_msg_result_current_shunt_init(struct v2_msg_result_current_shunt_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_msg_result_current_shunt_t));

    return 0;
}

bool v2_msg_result_current_shunt_mux_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_msg_result_current_shunt_message_count_is_in_range(int8_t value)
{
    return ((value >= -8) && (value <= 7));
}

bool v2_msg_result_current_shunt_result_state_is_in_range(int8_t value)
{
    return ((value >= -8) && (value <= 7));
}

bool v2_msg_result_current_shunt_current_result_is_in_range(int32_t value)
{
    (void)value;

    return (true);
}

int v2_max_min_volt_temp_pack(
    uint8_t *dst_p,
    const struct v2_max_min_volt_temp_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->max_volt, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->max_volt, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->min_volt, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->min_volt, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->max_temp, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->max_temp, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->min_temp, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->min_temp, 8u, 0xffu);

    return (8);
}

int v2_max_min_volt_temp_unpack(
    struct v2_max_min_volt_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_volt = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->max_volt |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->min_volt = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->min_volt |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->max_temp = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->max_temp |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->min_temp = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->min_temp |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int v2_max_min_volt_temp_init(struct v2_max_min_volt_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_max_min_volt_temp_t));

    return 0;
}

bool v2_max_min_volt_temp_max_volt_is_in_range(uint16_t value)
{
    return (value <= 5000u);
}

bool v2_max_min_volt_temp_min_volt_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_max_min_volt_temp_max_temp_is_in_range(uint16_t value)
{
    return (value <= 100u);
}

bool v2_max_min_volt_temp_min_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_9_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_9_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_9_unpack(
    struct v2_battery_info_9_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_9_init(struct v2_battery_info_9_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_9_t));

    return 0;
}

bool v2_battery_info_9_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_9_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_9_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_9_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_9_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_9_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_4_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_4_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_4_unpack(
    struct v2_battery_info_4_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_4_init(struct v2_battery_info_4_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_4_t));

    return 0;
}

bool v2_battery_info_4_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_4_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_4_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_4_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_4_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_4_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_8_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_8_unpack(
    struct v2_battery_info_8_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_8_init(struct v2_battery_info_8_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_8_t));

    return 0;
}

bool v2_battery_info_8_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_8_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_8_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_8_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_8_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_8_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_6_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_6_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_6_unpack(
    struct v2_battery_info_6_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_6_init(struct v2_battery_info_6_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_6_t));

    return 0;
}

bool v2_battery_info_6_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_6_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_6_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_6_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_6_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_6_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_7_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_7_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_7_unpack(
    struct v2_battery_info_7_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_7_init(struct v2_battery_info_7_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_7_t));

    return 0;
}

bool v2_battery_info_7_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_7_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_7_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_7_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_7_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_7_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_3_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_3_unpack(
    struct v2_battery_info_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_3_init(struct v2_battery_info_3_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_3_t));

    return 0;
}

bool v2_battery_info_3_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_3_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_3_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_3_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_3_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_3_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_12_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_12_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_12_unpack(
    struct v2_battery_info_12_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_12_init(struct v2_battery_info_12_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_12_t));

    return 0;
}

bool v2_battery_info_12_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_12_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_12_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_12_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_12_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_12_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_5_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_5_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_5_unpack(
    struct v2_battery_info_5_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_5_init(struct v2_battery_info_5_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_5_t));

    return 0;
}

bool v2_battery_info_5_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_5_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_5_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_5_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_5_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_5_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_2_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_2_unpack(
    struct v2_battery_info_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_2_init(struct v2_battery_info_2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_2_t));

    return 0;
}

bool v2_battery_info_2_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_2_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_2_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_2_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_2_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_2_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_11_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_11_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_11_unpack(
    struct v2_battery_info_11_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_11_init(struct v2_battery_info_11_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_11_t));

    return 0;
}

bool v2_battery_info_11_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_11_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_11_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_11_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_11_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_11_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_10_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_10_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_10_unpack(
    struct v2_battery_info_10_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_10_init(struct v2_battery_info_10_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_10_t));

    return 0;
}

bool v2_battery_info_10_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_10_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_10_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_10_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_10_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_10_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_1_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_1_unpack(
    struct v2_battery_info_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_1_init(struct v2_battery_info_1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_1_t));

    return 0;
}

bool v2_battery_info_1_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_1_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_1_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_1_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_1_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_1_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int v2_battery_info_13_pack(
    uint8_t *dst_p,
    const struct v2_battery_info_13_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->id, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->sfid, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->balance, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->rssi, 0u, 0xffu);

    return (8);
}

int v2_battery_info_13_unpack(
    struct v2_battery_info_13_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sfid = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->balance = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->rssi = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int v2_battery_info_13_init(struct v2_battery_info_13_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct v2_battery_info_13_t));

    return 0;
}

bool v2_battery_info_13_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_13_temp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_13_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_13_sfid_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool v2_battery_info_13_balance_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool v2_battery_info_13_rssi_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
